[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"

[fmt]
line_length = 100 
tab_width = 2
bracket_spacing = true
quote_style = "double"
wrap_comments = false 
single_line_statement_blocks = "single"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
